[theme]
base = "light"
primaryColor = "#4338CA"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F6FB"
textColor = "#1B2130"
font = "sans serif"

[client]
showErrorDetails = true

[browser]
gatherUsageStats = false
